name: Build and Deploy to gh-pages
on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Angular-Build
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2
      with:
        build_configuration: production
        base_href: gh-pages-test
        deploy_branch: gh-pages
        angular_dist_build_folder: dist/my-gh-pages-test
      
