name: Build and Deploy to gh-pages
on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Angular-Build
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@latest
      
